export const ADD_FAVORITE_MOVIES = 'ADD_FAVORITE_MOVIES';
export const REMOVE_FAVORITE_MOVIES = 'REMOVE_FAVORITE_MOVIES';
export const CHANGE_MOVIE = 'CHANGE_MOVIE';
export const NO_CHANGE_MOVIE = 'NO_CHANGE_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const FAVORITE_TOGGLE = 'FAVORITE_TOGGLE';
export const SEARCH_DATA = 'SEARCH_DATA';
export const SET_PAGE_SEARCH_DATA = 'SET_PAGE_SEARCH_DATA';
export const SHOW_ALERT = 'SHOW_ALERT';


